<?php echo $form->renderAll(); ?>

<div class="login-welcome-text">
    <h1>Welcome to Housekeeping</h1>

    <p>Welcome to Housekeeping. This service is monitored closely, with 24 hour IP address records being taken.</p>
    <p>This service is meant for <b>staff</b> use only. The service is monitored closely and we will pursue and charge any unauthorised users.</p>
    <p>Your username and password to this area are personal. <b>Never</b> give them to anyone under <b>any</b> circumstances.</p>
</div>