<body id="login">
    <div class="container">
        <?php echo $this->getContent(); ?>
    </div>

    <footer>
        <p>oldHabbo is not affiliated with, endorsed, sponsored, or specifically approved by Sulake Corporation Oy or its affiliates.</p>
        <p>Sulake is not responsible for any content on oldHabbo and the views and opinions expressed herein are not necessarily the views and opinions of Sulake.</p>
    </footer>
</body>