<body id="dashboard">
    <div class="container">
        <header>
            <p>Login: <b>ShortHabb</b></p>
            <a href="/logout">Log out</a>
        </header>

        <nav class="menu">
            <div class="menu-item">
                <p class="menu-heading">Hobba discussion board</p>

                <ul class="menu-item-entries">
                    <li class="menu-item-entry">
                        <a class="menu-link" href="/hobba/board/">Forums</a>
                    </li>
                </ul>
            </div>

            <div class="menu-item">
                <p class="menu-heading">Hobba tools</p>

                <ul>
                    <li>Remote alerting</li>
                    <li>Remote banning and kicking</li>
                    <li>List of current bans</li>
                    <li>Room admin</li>
                </ul>
            </div>
        </nav>

        <div class="menu">
            <p class="menu-heading">Hobba tools</p>

            <nav>
                <ul>
                    <li>Remote alerting</li>
                    <li>Remote banning and kicking</li>
                    <li>List of current bans</li>
                    <li>Room admin</li>
                </ul>
            </nav>
        </div>

        <div class="menu">
            <p class="menu-heading">Supervisor Hobba tools</p>

            <nav>
                <ul>
                    <li>Hobba activity log</li>
                    <li>Mass ban</li>
                    <li>Mass alert</li>
                </ul>
            </nav>
        </div>

        <div class="menu">
            <p class="menu-heading">Scam detection</p>

            <nav>
                <ul>
                    <li>Habbo search & information tool</li>
                    <li>Current furniture</li>
                </ul>
            </nav>
        </div>

        <div class="menu">
            <p class="menu-heading">Private rooms</p>

            <nav>
                <ul>
                    <li>Room admin</li>
                    <li>Room action log</li>
                    <li>Top-rated flats</li>
                    <li>Stickie viewer</li>
                </ul>
            </nav>
        </div>

        <div class="menu">
            <p class="menu-heading">Status</p>

            <nav>
                <ul>
                    <li>Payment status</li>
                </ul>
            </nav>
        </div>

        <div class="menu">
            <p class="menu-heading">Staff moderator tools</p>

            <nav>
                <ul>
                    <li>Mass unban</li>
                    <li>Habbo restore tool</li>
                    <li>Habbo name changer</li>
                </ul>
            </nav>
        </div>

        <div class="menu">
            <p class="menu-heading">Customer service</p>

            <nav>
                <ul>
                    <li>CS picker</li>
                    <li>Habbo problem reports</li>
                    <li>Calls for help</li>
                    <li>Reported messages</li>
                    <li>Feedback messages</li>
                    <li>Bug reports</li>
                    <li>Email opt-out list admin</li>
                </ul>
            </nav>
        </div>

        <div class="menu">
            <p class="menu-heading">Hobba tracking tools</p>

            <nav>
                <ul>
                    <li>Banned Habbos trying to enter</li>
                    <li>Hobba availability</li>
                    <li>Hobbo events by time of day</li>
                    <li>Hobba events by date</li>
                    <li>Calls for help</li>
                    <li>Mass unban</li>
                    <li>Habbo restore tool</li>
                    <li>Habbo name changer</li>
                </ul>
            </nav>
        </div>

        <div class="menu">
            <p class="menu-heading">Hobba management tools</p>

            <nav>
                <ul>
                    <li>Hobba rights editor</li>
                    <li>Hobba applications</li>
                    <li>Check Hobba applicant</li>
                </ul>
            </nav>
        </div>

        <?php echo $this->getContent(); ?>
    </div>
</body>